config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get "tasks", to: "tasks#index"
get "tasks/new", to: "tasks#new"
post "tasks", to: "tasks#create"
get "tasks/:id", to: "tasks#show", as: :task
get "tasks/:id/edit", to: "tasks#edit", as: :edit
patch "tasks/:id", to: "tasks#update"
delete "restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # => READ
  def index
   @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  # => CREATE
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
  <div class="container justify-content-center d-flex">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <div class="form-group">
    <%= t.label :title %>
    <%= t.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= t.check_box :completed, class:"form-check-input" %>
  </div>
  <%= t.submit%>
<% end %>
<%= link_to "back to tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1> My Tasks <h1><br>
<% @tasks.each do |task| %>
  <div>
    <% if (task.completed) %>
      <i class="far fa-check-square"></i>
    <% else %>
      <i class="far fa-square"></i>
    <% end %>
    <%= link_to "#{task.title}", task_path(task[:id]) %>
  </div>
<% end %>
<%= link_to "+ Add new task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
<%= t.label :title %>
<%= t.text_field :title %>
<%= t.label :details %>
<%= t.text_field :details %>
<%= t.submit %>
<% end  %>
<%= link_to "back to tasks", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "back to tasks", tasks_path %>
<%= link_to "edit", edit_path %>
<%= link_to "Delete", method: :delete, data: { confirm: "Are you sure?" } %>